### ISSUE TITLE
Pinyin features

### ISSUE THREAD

**Issue by lemmih** [sotch-pr35mac/prettify_pinyin#9]
Hi Preston,

There are a few behaviors that would be useful for me:

| Input | Current output | My desired output |
| :---: | :--------------: | :-----------------: |
| ni0 | {empty} | ni0 |
| má1 | {empty} | mā |
| nǐ0 | {empty} | ni |

It would suit my purposes if: (1) non-tone numbers were passed through without modifications, (2) tone marks could be replaced, and (3) tone marks could be cleared.

Would you accept PRs for such changes?

**Comment by sotch-pr35mac** [comment]
I'd absolutely be open to PRs for such changes.

**Comment by sotch-pr35mac** [comment]
@lemmih  Merged in the two PRs you had up for this, does that just about close out this issue?
